"""A procedural yard with known ground truth: many plants, a building and ground, as splats.

``synthetic_tree.py`` answers "which splat belongs to which branch" for one tree. Living Mode
for a whole capture asks a different question first -- which splats are plants at all, which
plant each belongs to, and what kind of plant it is -- and on a real capture nobody knows the
answer. This module builds a scene where it is known by construction, the way
``synthetic_tree.py`` does for branches: every splat is generated as part of one object and
that object's class and instance are written out beside it.

The scene, in a local east-north-up frame (metres, +Z up), on gently undulating ground:

* **leafy trees** of three sizes, each a ``synthetic_tree_rig`` skeleton clothed by
  ``synthetic_tree.generate_splats`` (bark and leaf sleeves) -- one of them deliberately sparse,
  so a scene step has to choose the crown rig for it;
* **a cluster of shrubs**, 0.5-2 m, leafy ellipsoids on a few short stems;
* **two snags**: bare trunks, 7 and 10 m, bark-coloured, with a couple of broken stubs;
* **a box building** with a pitched roof, grey walls and a red roof;
* **ground**: a lawn (green, with tufts a few centimetres high) and a gravel path (grey-brown).

Classes follow ``scene_plants.CLASSES``: tree, shrub, snag, grass/low, ground, other-static.

It writes, into ``<out_dir>``::

    source/splat.ply      binary little-endian 3DGS PLY, the layout splat_tiles reads
    source/labels.json    per splat, in PLY order: class index and instance index; the
                          instances (id, class, stem, height) and the class names
    splat/                a level-of-detail tileset (splat_tiles.convert), small tiles so the
                          yard is many tiles and merged parents, as a real capture is, and
                          beside it what the scene step makes of it (scene_plants.build):
                          rig.json, motion.json, plants.json, scene.json (with its score
                          against the truth), ground.f32, classes.u8

Only ``splat/`` is committed (data/tiles/synthetic-yard): ``source/`` is regenerated by the
test that checks the committed tiles are still byte-identical to a fresh run.

Byte-reproducible, like the tree: seeded RNG, positions snapped to the SPZ grid.

Usage (OpenBLAS pinned as tests/conftest.py pins it, so the bytes are the CPU's own no more):
    OPENBLAS_CORETYPE=Haswell python synthetic_yard.py ../../data/tiles/synthetic-yard \
        [--seed 11] [--tile-gaussians 6000]
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

import numpy as np

import scene_plants
import splat_tiles
from synthetic_tree import (
    POSITION_QUANTUM,
    _orthonormal_frame,
    _random_quats_wxyz,
    generate_splats,
    synthetic_tree_rig,
    write_ply,
)

#: Class names, in the order ``labels.json`` indexes them. Mirrors ``scene_plants.CLASSES``.
CLASSES = ("tree", "shrub", "snag", "grass/low", "ground", "other-static")

#: The yard's extent, metres east and north of its south-west corner.
EXTENT_M = (32.0, 24.0)
#: Ground splats per square metre: a phone or drone capture's surface is of this order.
GROUND_DENSITY = 22.0
#: Amplitude of the ground's undulation, metres, and its wavelength: a garden, not a table.
GROUND_RELIEF_M = 0.35
GROUND_WAVELENGTH_M = 17.0

LAWN_RGB = (0.36, 0.56, 0.21)
PATH_RGB = (0.47, 0.43, 0.37)
BARK_RGB = (0.36, 0.28, 0.21)
SHRUB_RGB = (0.20, 0.44, 0.16)
WALL_RGB = (0.72, 0.71, 0.68)
ROOF_RGB = (0.56, 0.22, 0.17)

#: The leafy trees: (east, north, height m, splats, whorls). The 11 m tree carries a quarter
#: of the density per metre of the others, which puts it under the skeleton's evidence bar.
TREES = (
    (8.0, 17.0, 6.5, 7000, 4),
    (21.0, 19.5, 9.0, 9000, 4),
    (27.5, 7.0, 11.0, 2600, 5),
)
#: The shrubs: (east, north, height m, crown radius m, splats).
SHRUBS = (
    (12.5, 5.0, 1.4, 0.75, 900),
    (14.4, 5.6, 0.9, 0.55, 600),
    (13.3, 7.1, 2.0, 0.95, 1300),
    (15.9, 7.2, 0.6, 0.45, 400),
    (11.4, 6.9, 1.1, 0.6, 700),
)
#: The snags: (east, north, height m, base diameter m, splats).
SNAGS = (
    (4.0, 5.0, 7.0, 0.42, 1300),
    (29.5, 20.5, 10.0, 0.5, 1800),
)
#: The building: south-west corner, size (east, north, eave height), ridge rise, wall splats
#: per square metre.
BUILDING = {"corner": (17.0, 4.0), "size": (6.0, 4.5, 3.2), "ridge": 1.4, "density": 14.0}
#: The path: a strip from west to east, metres north, half-width.
PATH = (12.0, 0.9)


def ground_height(x: np.ndarray, y: np.ndarray) -> np.ndarray:
    """The yard's terrain, metres: a smooth two-component undulation."""
    k = 2.0 * math.pi / GROUND_WAVELENGTH_M
    return GROUND_RELIEF_M * (0.6 * np.sin(k * x + 0.4) * np.cos(0.7 * k * y) + 0.4 * np.sin(k * y))


class _Parts:
    """Per-splat arrays, one append per generated group, each tagged with class and instance."""

    def __init__(self) -> None:
        self.columns: dict[str, list[np.ndarray]] = {
            key: [] for key in ("position", "rgb", "opacity_logit", "log_scale", "quat_wxyz")
        }
        self.klass: list[np.ndarray] = []
        self.instance: list[np.ndarray] = []

    def add(self, data: dict[str, np.ndarray], klass: int, instance: int) -> None:
        count = int(data["position"].shape[0])
        for key, parts in self.columns.items():
            parts.append(np.asarray(data[key], dtype=np.float64))
        self.klass.append(np.full(count, klass, dtype=np.int32))
        self.instance.append(np.full(count, instance, dtype=np.int32))

    def stacked(self) -> tuple[dict[str, np.ndarray], np.ndarray, np.ndarray]:
        data = {key: np.concatenate(parts, axis=0) for key, parts in self.columns.items()}
        return data, np.concatenate(self.klass), np.concatenate(self.instance)


def _flat_discs(
    rng: np.random.Generator, normals: np.ndarray, size: np.ndarray, thin: float
) -> tuple[np.ndarray, np.ndarray]:
    """Log-scales and w-first quaternions of discs lying across the given normals."""
    quats = np.empty((normals.shape[0], 4))
    for i, normal in enumerate(normals):
        e0, e1, e2 = _orthonormal_frame(normal)
        m = np.stack([e1, e2, e0], axis=1)
        # A rotation matrix to a quaternion, the trace branch (these frames are proper).
        w = math.sqrt(max(1.0 + m[0, 0] + m[1, 1] + m[2, 2], 1e-12)) / 2.0
        quats[i] = [
            w,
            (m[2, 1] - m[1, 2]) / (4 * w),
            (m[0, 2] - m[2, 0]) / (4 * w),
            (m[1, 0] - m[0, 1]) / (4 * w),
        ]
    quats /= np.linalg.norm(quats, axis=1, keepdims=True)
    jitter = 0.8 + 0.4 * rng.random((normals.shape[0], 2))
    scale = np.stack([size * jitter[:, 0], size * jitter[:, 1], np.full(size.shape, thin)], axis=1)
    return np.log(np.maximum(scale, 1e-4)), quats


def _ground(rng: np.random.Generator, parts: _Parts) -> None:
    """Lawn and path: discs on the terrain, the lawn with low tufts."""
    area = EXTENT_M[0] * EXTENT_M[1]
    count = int(area * GROUND_DENSITY)
    x = rng.random(count) * EXTENT_M[0]
    y = rng.random(count) * EXTENT_M[1]
    on_path = np.abs(y - PATH[0] - 0.8 * np.sin(x / 5.0)) < PATH[1]
    # Nothing under the building's footprint: it stands on a slab of its own.
    bx, by = BUILDING["corner"]
    bw, bd, _ = BUILDING["size"]
    under = (x > bx - 0.05) & (x < bx + bw + 0.05) & (y > by - 0.05) & (y < by + bd + 0.05)
    x, y, on_path = x[~under], y[~under], on_path[~under]
    count = int(x.size)
    z = ground_height(x, y)
    # Grass tufts stand a few centimetres proud of the soil; the path is flat.
    tuft = np.where(on_path, 0.0, 0.07 * rng.random(count) ** 2)
    position = np.stack([x, y, z + tuft], axis=1)
    base = np.where(on_path[:, None], np.asarray(PATH_RGB), np.asarray(LAWN_RGB))
    rgb = np.clip(base * (0.8 + 0.4 * rng.random((count, 1))), 0.0, 1.0)
    normals = np.tile(np.array([0.0, 0.0, 1.0]), (count, 1)) + 0.25 * rng.standard_normal(
        (count, 3)
    )
    log_scale, quats = _flat_discs(rng, normals, np.full(count, 0.11), 0.012)
    data = {
        "position": position,
        "rgb": rgb,
        "opacity_logit": 2.0 + rng.random(count),
        "log_scale": log_scale,
        "quat_wxyz": quats,
    }
    lawn = ~on_path
    parts.add({k: v[lawn] for k, v in data.items()}, CLASSES.index("grass/low"), -1)
    parts.add({k: v[on_path] for k, v in data.items()}, CLASSES.index("ground"), -1)


def _tree(
    rng_seed: int, east: float, north: float, height: float, splats: int, whorls: int
) -> dict[str, np.ndarray]:
    """A synthetic_tree clothed in its own splats, moved to its stem point on the terrain."""
    rig = synthetic_tree_rig(height_m=height, whorls=whorls)
    data = generate_splats(rig, splats, rng_seed, height)
    base = float(ground_height(np.asarray([east]), np.asarray([north]))[0])
    data["position"] = data["position"].astype(np.float64) + np.asarray([east, north, base])
    return data


def _shrub(
    rng: np.random.Generator, east: float, north: float, height: float, radius: float, count: int
) -> dict[str, np.ndarray]:
    """A leafy ellipsoid on three short stems, a hand's width above the lawn."""
    base = float(ground_height(np.asarray([east]), np.asarray([north]))[0])
    stems = max(3, count // 12)
    leaves = count - stems
    # Leaves on and just inside the crown's surface: a shrub is seen as its outer shell.
    direction = rng.standard_normal((leaves, 3))
    direction /= np.linalg.norm(direction, axis=1, keepdims=True)
    depth = 1.0 - 0.25 * rng.random(leaves) ** 2
    half = height / 2.0
    centre = np.asarray([east, north, base + 0.08 + half * 0.95])
    leaf_pos = centre + direction * np.stack(
        [radius * depth, radius * depth, half * 0.95 * depth], axis=1
    )
    leaf_pos[:, 2] = np.maximum(leaf_pos[:, 2], base + 0.08)
    leaf_rgb = np.clip(np.asarray(SHRUB_RGB) * (0.75 + 0.5 * rng.random((leaves, 3))), 0.0, 1.0)
    leaf_scale, leaf_quat = _flat_discs(rng, direction, np.full(leaves, 0.035), 0.006)
    # Stems: short woody sticks from the ground into the crown.
    t = rng.random(stems)
    angle = rng.random(stems) * 2 * math.pi
    stem_pos = np.stack(
        [
            east + 0.25 * radius * np.cos(angle) * t,
            north + 0.25 * radius * np.sin(angle) * t,
            base + t * height * 0.55,
        ],
        axis=1,
    )
    stem_rgb = np.clip(np.asarray(BARK_RGB) * (0.8 + 0.3 * rng.random((stems, 1))), 0.0, 1.0)
    stem_scale = np.log(np.tile([0.03, 0.012, 0.012], (stems, 1)))
    return {
        "position": np.concatenate([leaf_pos, stem_pos]),
        "rgb": np.concatenate([leaf_rgb, stem_rgb]),
        "opacity_logit": 1.6 + 0.8 * rng.random(count),
        "log_scale": np.concatenate([leaf_scale, stem_scale]),
        "quat_wxyz": np.concatenate([leaf_quat, _random_quats_wxyz(rng, stems)]),
    }


def _snag(
    rng: np.random.Generator, east: float, north: float, height: float, diameter: float, count: int
) -> dict[str, np.ndarray]:
    """A bare trunk: a tapering bark cylinder, a slight lean, two short broken stubs."""
    base = float(ground_height(np.asarray([east]), np.asarray([north]))[0])
    stubs = count // 10
    trunk = count - stubs
    t = (np.arange(trunk) + rng.random(trunk)) / trunk
    radius = 0.5 * diameter * (1.0 - 0.55 * t) * (0.93 + 0.14 * rng.random(trunk))
    theta = rng.random(trunk) * 2 * math.pi
    lean = np.asarray([0.03, 0.015]) * height
    centre = np.stack(
        [east + lean[0] * t**2, north + lean[1] * t**2, base - 0.05 + t * height], axis=1
    )
    offset = np.stack([radius * np.cos(theta), radius * np.sin(theta), np.zeros(trunk)], axis=1)
    normals = offset / np.maximum(np.linalg.norm(offset, axis=1, keepdims=True), 1e-9)
    pos = centre + offset
    log_scale, quats = _flat_discs(rng, normals, np.full(trunk, 0.06), 0.01)
    # Two stubs: short, thick, pointing out and a little down, where limbs broke off.
    stub_pos = []
    for k in range(stubs):
        which = k % 2
        at = (0.45, 0.7)[which] * height
        azimuth = (0.8, 3.6)[which]
        run = rng.random() * 0.6
        stub_pos.append(
            [
                east + lean[0] * (at / height) ** 2 + math.cos(azimuth) * run,
                north + lean[1] * (at / height) ** 2 + math.sin(azimuth) * run,
                base + at - 0.15 * run + 0.05 * rng.standard_normal(),
            ]
        )
    stub = np.asarray(stub_pos)
    grey = np.asarray(BARK_RGB) * np.asarray([1.05, 1.05, 1.1])
    rgb = np.clip(grey * (0.75 + 0.4 * rng.random((count, 1))), 0.0, 1.0)
    return {
        "position": np.concatenate([pos, stub]),
        "rgb": rgb,
        "opacity_logit": 2.0 + 0.6 * rng.random(count),
        "log_scale": np.concatenate([log_scale, np.log(np.tile([0.05, 0.03, 0.03], (stubs, 1)))]),
        "quat_wxyz": np.concatenate([quats, _random_quats_wxyz(rng, stubs)]),
    }


def _building(rng: np.random.Generator) -> dict[str, np.ndarray]:
    """Four walls and a pitched roof as flat splats on the faces, on a level slab."""
    (x0, y0), (w, d, eave), ridge = BUILDING["corner"], BUILDING["size"], BUILDING["ridge"]
    density = BUILDING["density"]
    slab = float(ground_height(np.asarray([x0 + w / 2]), np.asarray([y0 + d / 2]))[0]) - 0.1
    positions, normals, colours = [], [], []

    def face(origin, u, v, normal, colour, area_scale=1.0) -> None:
        area = float(np.linalg.norm(np.cross(u, v))) * area_scale
        n = int(area * density)
        a, b = rng.random(n), rng.random(n)
        positions.append(np.asarray(origin) + np.outer(a, u) + np.outer(b, v))
        normals.append(np.tile(normal, (n, 1)))
        colours.append(np.tile(colour, (n, 1)))

    z = slab
    face((x0, y0, z), (w, 0, 0), (0, 0, eave), (0, -1, 0), WALL_RGB)
    face((x0, y0 + d, z), (w, 0, 0), (0, 0, eave), (0, 1, 0), WALL_RGB)
    face((x0, y0, z), (0, d, 0), (0, 0, eave), (-1, 0, 0), WALL_RGB)
    face((x0 + w, y0, z), (0, d, 0), (0, 0, eave), (1, 0, 0), WALL_RGB)
    # Gables: triangles, drawn as a rectangle and kept below the roof line.
    for gx, nx in ((x0, -1), (x0 + w, 1)):
        n = int(0.5 * d * ridge * density)
        a, b = rng.random(n), rng.random(n)
        yy = y0 + a * d
        top = z + eave + ridge * (1 - np.abs(2 * a - 1))
        zz = z + eave + b * (top - z - eave)
        positions.append(np.stack([np.full(n, gx), yy, zz], axis=1))
        normals.append(np.tile((nx, 0, 0), (n, 1)))
        colours.append(np.tile(WALL_RGB, (n, 1)))
    slope = math.hypot(d / 2, ridge)
    for side in (0, 1):
        n = int(w * slope * density)
        a, b = rng.random(n), rng.random(n)
        yy = y0 + (b * d / 2 if side == 0 else d - b * d / 2)
        zz = z + eave + b * ridge
        positions.append(np.stack([x0 + a * w, yy, zz], axis=1))
        ny = -d / 2 if side == 0 else d / 2
        normal = np.asarray([0.0, ny, 2 * ridge]) / math.hypot(ny, 2 * ridge)
        normals.append(np.tile(normal, (n, 1)))
        colours.append(np.tile(ROOF_RGB, (n, 1)))
    position = np.concatenate(positions)
    normal = np.concatenate(normals).astype(np.float64)
    count = int(position.shape[0])
    log_scale, quats = _flat_discs(rng, normal, np.full(count, 0.16), 0.01)
    rgb = np.clip(np.concatenate(colours) * (0.9 + 0.2 * rng.random((count, 1))), 0.0, 1.0)
    return {
        "position": position,
        "rgb": rgb,
        "opacity_logit": 2.4 + 0.4 * rng.random(count),
        "log_scale": log_scale,
        "quat_wxyz": quats,
    }


def generate_yard(seed: int = 11) -> tuple[dict[str, np.ndarray], np.ndarray, np.ndarray, list]:
    """Every splat of the yard, with its class and instance, and the instance table."""
    rng = np.random.default_rng(seed)
    parts = _Parts()
    instances: list[dict] = []

    def instance(klass: str, east: float, north: float, height: float) -> int:
        base = float(ground_height(np.asarray([east]), np.asarray([north]))[0])
        instances.append(
            {
                "id": f"{klass}-{sum(1 for i in instances if i['class'] == klass)}",
                "class": klass,
                "stem": [east, north, round(base, 4)],
                "heightM": height,
            }
        )
        return len(instances) - 1

    _ground(rng, parts)
    for k, (east, north, height, splats, whorls) in enumerate(TREES):
        data = _tree(seed * 101 + k, east, north, height, splats, whorls)
        top = float(data["position"][:, 2].max())
        base = float(ground_height(np.asarray([east]), np.asarray([north]))[0])
        index = instance("tree", east, north, round(top - base, 3))
        parts.add(data, CLASSES.index("tree"), index)
    for east, north, height, radius, splats in SHRUBS:
        index = instance("shrub", east, north, height)
        parts.add(_shrub(rng, east, north, height, radius, splats), CLASSES.index("shrub"), index)
    for east, north, height, diameter, splats in SNAGS:
        index = instance("snag", east, north, height)
        parts.add(_snag(rng, east, north, height, diameter, splats), CLASSES.index("snag"), index)
    parts.add(_building(rng), CLASSES.index("other-static"), -1)

    data, klass, inst = parts.stacked()
    snapped = (np.round(data["position"] / POSITION_QUANTUM) * POSITION_QUANTUM).astype(np.float32)
    snapped[snapped == 0.0] = 0.0
    data["position"] = snapped
    return data, klass, inst, instances


def generate(
    out_dir: Path,
    *,
    seed: int = 11,
    lat: float = 46.1335,
    lon: float = -123.8800,
    height: float = 0.0,
    tile_gaussians: int = 6000,
    plants: bool = True,
) -> dict:
    """Write the yard's PLY, labels and level-of-detail tileset. Returns a summary."""
    data, klass, inst, instances = generate_yard(seed)
    source_dir = out_dir / "source"
    source_dir.mkdir(parents=True, exist_ok=True)
    ply = source_dir / "splat.ply"
    write_ply(ply, data)
    (source_dir / "labels.json").write_text(
        json.dumps(
            {
                "note": "ground truth per splat, in PLY order: class index into classes, "
                "instance index into instances (-1 for none)",
                "classes": list(CLASSES),
                "instances": instances,
                "class": [int(v) for v in klass],
                "instance": [int(v) for v in inst],
            },
            separators=(",", ":"),
        )
        + "\n",
        encoding="utf-8",
    )
    stats = splat_tiles.convert(
        ply, out_dir / "splat", lat, lon, height, opacity_min=0.02, tile_gaussians=tile_gaussians
    )
    summary: dict = {
        "splats": int(klass.size),
        "instances": len(instances),
        "tiles": stats["tiles"],
        "dropped": stats["dropped"],
        "out_dir": str(out_dir),
    }
    if plants:
        truth = json.loads((source_dir / "labels.json").read_text(encoding="utf-8"))
        report = scene_plants.build(
            ply,
            out_dir / "splat",
            tiles_dir=out_dir / "splat",
            opacity_min=0.02,
            tile_gaussians=tile_gaussians,
            truth=truth,
        )
        summary["score"] = report["score"]
        summary["timingsS"] = report["timingsS"]
    return summary


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("out_dir", type=Path)
    parser.add_argument("--seed", type=int, default=11)
    # Fort Clatsop's latitude and longitude, so the fixture can be flown to where the real
    # capture it stands in for will sit. Nothing in the scene step reads them.
    parser.add_argument("--lat", type=float, default=46.1335)
    parser.add_argument("--lon", type=float, default=-123.8800)
    parser.add_argument("--height", type=float, default=0.0)
    parser.add_argument("--tile-gaussians", type=int, default=6000)
    parser.add_argument("--no-plants", action="store_true", help="skip the scene step")
    args = parser.parse_args()
    print(
        json.dumps(
            generate(
                args.out_dir,
                seed=args.seed,
                lat=args.lat,
                lon=args.lon,
                height=args.height,
                tile_gaussians=args.tile_gaussians,
                plants=not args.no_plants,
            ),
            indent=1,
        )
    )


if __name__ == "__main__":
    main()
