/**
 * Demo mission data for the public Cesium demo site.
 *
 * The fleet, zones and plans are SIMULATED (the UI says so). Their geometry is
 * anchored inside the demo site's real footprint so they sit on the reality model.
 */

import { DEMO_SITE_SLUG } from "@/api/fallback";

import type { MissionProvider, Project, Zone } from "./types";

function polygon(points: [number, number][]): Zone["footprint"] {
  const first = points[0] ?? [0, 0];
  return { type: "Polygon", coordinates: [[...points, first]] };
}

export const DEMO_PROJECT: Project = {
  id: "demo-blackrock",
  siteId: null,
  name: "Blackrock Mesa",
  meta: "1,185 acres · invasives removal",
  simulated: true,
  machines: [
    {
      id: "TR-04",
      name: "TR-04 Kestrel",
      model: "Ranger 2 · mower",
      task: "Mowing",
      status: "working",
      position: { longitude: -122.1385, latitude: 47.645 },
      headingDeg: 34,
      batteryPct: 82,
      acresDone: 239,
      shift: "6:14",
      zoneLabel: "Z-14 west",
      primaryAction: "Pause",
      track: [
        { longitude: -122.1395, latitude: 47.6421 },
        { longitude: -122.139, latitude: 47.6428 },
        { longitude: -122.1381, latitude: 47.6435 },
        { longitude: -122.1388, latitude: 47.6442 },
        { longitude: -122.1385, latitude: 47.645 },
      ],
    },
    {
      id: "TR-12",
      name: "TR-12 Pipit",
      model: "Ranger 2 · mower",
      task: "Mowing",
      status: "working",
      position: { longitude: -122.1399, latitude: 47.6587 },
      headingDeg: 302,
      batteryPct: 67,
      acresDone: 181,
      shift: "4:02",
      zoneLabel: "Z-21 north",
      primaryAction: "Pause",
    },
    {
      id: "TR-07",
      name: "TR-07 Harrier",
      model: "Ranger 2 · mower",
      task: "Service due",
      status: "attention",
      position: { longitude: -122.1273, latitude: 47.6431 },
      headingDeg: 128,
      batteryPct: 41,
      acresDone: 96,
      shift: "2:40",
      zoneLabel: "Holding",
      primaryAction: "Recall",
    },
    {
      id: "TR-18",
      name: "TR-18 Shrike",
      model: "Scout 1 · survey",
      task: "Low signal",
      status: "attention",
      position: { longitude: -122.1282, latitude: 47.64 },
      headingDeg: 210,
      batteryPct: 54,
      acresDone: null,
      shift: "5:31",
      zoneLabel: "Z-08 draw",
      primaryAction: "Retry link",
    },
    {
      id: "TR-11",
      name: "TR-11 Vireo",
      model: "Scout 1 · survey",
      task: "Docked",
      status: "idle",
      position: { longitude: -122.125, latitude: 47.6404 },
      headingDeg: 0,
      batteryPct: 96,
      acresDone: 0,
      shift: "0:00",
      zoneLabel: "Base 2",
      primaryAction: "Deploy",
    },
    {
      id: "TR-15",
      name: "TR-15 Towhee",
      model: "Drill 1 · seeder",
      task: "Loading seed",
      status: "idle",
      position: { longitude: -122.1415, latitude: 47.6431 },
      headingDeg: 90,
      batteryPct: 88,
      acresDone: 0,
      shift: "1:18",
      zoneLabel: "Base 1",
      primaryAction: "Deploy",
    },
  ],
  zones: [
    {
      id: "Z-14",
      name: "Z-14 West bench",
      short: "mowing 58%",
      tone: "teal",
      treated: true,
      acres: 312,
      task: "Mow invasive belts",
      machines: "TR-04, TR-12",
      progressPct: 58,
      note: "182 ac cut. Second pass starts Thursday 06:00.",
      anchor: { longitude: -122.1374, latitude: 47.6481 },
      footprint: polygon([
        [-122.1398, 47.6486],
        [-122.1328, 47.6487],
        [-122.1329, 47.6419],
        [-122.1399, 47.6421],
      ]),
    },
    {
      id: "Z-21",
      name: "Z-21 North fence",
      short: "buffer queued",
      tone: "amber",
      treated: false,
      acres: 218,
      task: "Buffer + mow queued",
      machines: "TR-12 (queued)",
      progressPct: 12,
      note: "Agent redrew the 15 m fence offset; awaiting your approval.",
      anchor: { longitude: -122.1401, latitude: 47.6594 },
      footprint: polygon([
        [-122.142, 47.6599],
        [-122.1381, 47.6598],
        [-122.1382, 47.6574],
        [-122.1419, 47.6574],
      ]),
    },
    {
      id: "Z-08",
      name: "Z-08 Draw",
      short: "survey sweep",
      tone: "blue",
      treated: false,
      acres: 146,
      task: "Transect survey",
      machines: "TR-18",
      progressPct: 34,
      note: "Imagery gap in the north half — TR-18 link is weak.",
      anchor: { longitude: -122.1282, latitude: 47.6436 },
      footprint: polygon([
        [-122.1318, 47.644],
        [-122.1246, 47.6441],
        [-122.1246, 47.6386],
        [-122.1319, 47.6385],
      ]),
    },
  ],
  plans: [
    {
      id: "thistle",
      title: "Remove all invasive star thistle",
      state: "Behind",
      status: "warn",
      meta: "Treatment · Z-14, Z-21 · 530 acres",
      progressPct: 58,
      progressLabel: "58%",
      objective:
        "Cut and clear yellow star thistle across the two infested belts before seed set, then hold the ground with two follow-up passes each season until cover drops under 10%.",
      stats: [
        { value: "308", label: "Acres cut" },
        { value: "2", label: "Machines" },
        { value: "11 d", label: "Behind plan", accent: true },
      ],
      facts: [
        { k: "Cadence", v: "Two passes per season, spring and late summer" },
        { k: "Next run", v: "Thursday 06:00 · TR-04, TR-12" },
        { k: "Area", v: "Z-14 west bench, Z-21 north fence" },
        { k: "Target", v: "Cover under 10% by 2028" },
      ],
      agentNote: "Revised mow sequence recovers 11 days. Waiting on your approval.",
      action: "Pause plan",
      span: "Mar 2 – Nov 20, 2026",
      start: "Mar 2",
      end: "Nov 20, 2026",
      todayPct: 65,
      ongoing: false,
      zoneIds: ["Z-14", "Z-21"],
    },
    {
      id: "pipeline",
      title: "Inspect pipeline for damage once per month",
      state: "On track",
      status: "ok",
      meta: "Recurring · 14 mi corridor · monthly",
      progressPct: 82,
      progressLabel: "9 of 11 runs",
      objective:
        "Fly the buried-line corridor monthly, capture imagery at 2 cm and flag erosion, exposed pipe and vehicle damage for the maintenance crew.",
      stats: [
        { value: "14", label: "Miles" },
        { value: "9", label: "Runs done" },
        { value: "3", label: "Open flags", accent: true },
      ],
      facts: [
        { k: "Cadence", v: "Monthly, first clear-weather day" },
        { k: "Next run", v: "Sep 26 · TR-18 Shrike" },
        { k: "Area", v: "North-south corridor, 30 m buffer" },
        { k: "Output", v: "Flagged imagery to the maintenance folder" },
      ],
      agentNote: "Two flags from the August run are still unresolved at mile 6.2 and 9.8.",
      action: "Pause plan",
      span: "Monthly since Jan 2025 · no end date",
      start: "Jan 2025",
      end: "Ongoing",
      todayPct: 0,
      ongoing: true,
      zoneIds: ["Z-08"],
    },
    {
      id: "survey3d",
      title: "Collect detailed 3D survey of ranch",
      state: "Running",
      status: "run",
      meta: "One-off · 1,185 acres · lidar + photogrammetry",
      progressPct: 62,
      progressLabel: "62%",
      objective:
        "Build a full terrain and canopy model of the property to support drainage planning, fuel load estimates and future change detection.",
      stats: [
        { value: "735", label: "Acres flown" },
        { value: "2 cm", label: "Resolution" },
        { value: "6 d", label: "Remaining", accent: true },
      ],
      facts: [
        { k: "Cadence", v: "One-off, repeat every 3 years" },
        { k: "Next run", v: "Tomorrow 07:15 · TR-11 Vireo" },
        { k: "Area", v: "Whole property, 12 survey blocks" },
        { k: "Output", v: "Point cloud, DSM, canopy height model" },
      ],
      agentNote: "Blocks 9 and 10 need a re-fly — cloud shadow exceeded tolerance.",
      action: "Pause plan",
      span: "Aug 24 – Sep 30, 2026",
      start: "Aug 24",
      end: "Sep 30, 2026",
      todayPct: 62,
      ongoing: false,
      zoneIds: ["Z-14", "Z-21", "Z-08"],
    },
    {
      id: "seed",
      title: "Drill native seed after first rain",
      state: "Queued",
      status: "idle",
      meta: "Seasonal window · 840 acres · Sep 23 – Oct 5",
      progressPct: 0,
      progressLabel: "Not started",
      objective:
        "Drill the native perennial mix into treated ground as soon as the first soaking rain lands, before the window closes in early October.",
      stats: [
        { value: "840", label: "Acres" },
        { value: "1", label: "Machine" },
        { value: "13 d", label: "Window left", accent: true },
      ],
      facts: [
        { k: "Cadence", v: "Annual, weather-triggered" },
        { k: "Trigger", v: "First 15 mm rain event" },
        { k: "Area", v: "Z-14, Z-03 flat, Z-21 south half" },
        { k: "Machine", v: "TR-15 Towhee · Drill 1" },
      ],
      agentNote:
        "Forecast shows no qualifying rain in the next 10 days. Seed is loaded and staged.",
      action: "Run now",
      span: "Sep 23 – Oct 5, 2026",
      start: "Sep 23",
      end: "Oct 5, 2026",
      todayPct: 0,
      ongoing: false,
      zoneIds: ["Z-14", "Z-21"],
    },
    {
      id: "fuelbreak",
      title: "Maintain fuel break along the north fence",
      state: "On track",
      status: "ok",
      meta: "Recurring · 6.4 mi · quarterly",
      progressPct: 74,
      progressLabel: "74%",
      objective:
        "Keep a 30 m mown break along the north property line to slow fire spread from the highway side.",
      stats: [
        { value: "6.4", label: "Miles" },
        { value: "30 m", label: "Width" },
        { value: "Q4", label: "Next cycle", accent: true },
      ],
      facts: [
        { k: "Cadence", v: "Quarterly" },
        { k: "Next run", v: "Oct 14 · TR-04 Kestrel" },
        { k: "Area", v: "North fence line, highway side" },
        { k: "Standard", v: "Under 10 cm residual height" },
      ],
      agentNote: "Last cycle finished two days early. No follow-up needed.",
      action: "Pause plan",
      span: "Quarterly since Apr 2024 · no end date",
      start: "Apr 2024",
      end: "Ongoing",
      todayPct: 0,
      ongoing: true,
      zoneIds: ["Z-21"],
    },
  ],
  agent: {
    headline: "Rebuilding the north-fence mow sequence",
    summary: "Working on the mow schedule",
    footer: "Plan recovers 11 days · review when ready",
    actions: [
      { id: "a1", text: "Sequencing passes against the 48 h wind forecast", status: "run" },
      { id: "a2", text: "Merging the buffer geometry into one revised task", status: "run" },
      { id: "a3", text: "Holding TR-12 for two passes from 06:00", status: "wait" },
      { id: "a4", text: "Drafting the gate and access note for the field crew", status: "wait" },
      { id: "a5", text: "Checking the mow finishes before the seed window", status: "wait" },
      { id: "a6", text: "Drew the 15 m fence buffer on Z-21 · 118 ac", status: "done" },
      { id: "a7", text: "Read slope, fence line and raptor setback layers", status: "done" },
      { id: "a8", text: "Pulled the 3-hourly forecast through Sunday", status: "done" },
      { id: "a9", text: "Found invasive cover as the only goal behind plan", status: "done" },
    ],
  },
  fleetStats: [
    { value: "4", label: "Working now" },
    { value: "214 ac", label: "Treated today" },
    { value: "92%", label: "Uptime, 7 days" },
    { value: "2", label: "Need attention", accent: true },
  ],
  fleetNote:
    "TR-07 blade wear at 86% — agent scheduled service Thursday and shifted its passes to TR-12.",
  workLog: [
    {
      date: "09-12",
      machine: "TR-04",
      task: "Mow pass 2",
      acres: 62,
      hours: "5:40",
      rate: "0.38",
      zone: "Z-14 west",
      tone: "teal",
    },
    {
      date: "09-12",
      machine: "TR-12",
      task: "Mow pass 1",
      acres: 48,
      hours: "4:10",
      rate: "0.44",
      zone: "Z-21 north",
      tone: "teal",
    },
    {
      date: "09-11",
      machine: "TR-18",
      task: "Transect survey",
      acres: 146,
      hours: "3:05",
      rate: "—",
      zone: "Z-08 draw",
      tone: "blue",
    },
    {
      date: "09-10",
      machine: "TR-04",
      task: "Mow pass 1",
      acres: 71,
      hours: "6:20",
      rate: "0.41",
      zone: "Z-14 west",
      tone: "teal",
    },
    {
      date: "09-09",
      machine: "TR-07",
      task: "Mow pass 1",
      acres: 34,
      hours: "3:15",
      rate: "0.52",
      zone: "Z-21 north",
      tone: "amber",
    },
    {
      date: "09-08",
      machine: "TR-15",
      task: "Seed drill trial",
      acres: 18,
      hours: "1:45",
      rate: "—",
      zone: "Z-03 flat",
      tone: "neutral",
    },
    {
      date: "09-05",
      machine: "TR-12",
      task: "Mow pass 1",
      acres: 58,
      hours: "5:05",
      rate: "0.40",
      zone: "Z-14 east",
      tone: "teal",
    },
  ],
  feeds: [
    { id: "TR-04", camera: "front", state: "live", time: "14:22:06" },
    { id: "TR-12", camera: "front", state: "live", time: "14:22:06" },
    { id: "TR-18", camera: "mast", state: "weak", time: "14:21:58" },
    { id: "TR-15", camera: "hopper", state: "idle", time: "14:22:04" },
  ],
};

/** Attaches the simulated demo project to the public Cesium demo site. */
export class DemoMissionProvider implements MissionProvider {
  readonly name = "demo";

  projectForSite(siteId: string | null, siteSlug: string | null): Project | null {
    if (siteSlug === DEMO_SITE_SLUG || siteId?.startsWith("builtin-")) {
      return { ...DEMO_PROJECT, siteId };
    }
    return null;
  }
}
