"""The synthetic tree is the fixture the Living Survey runtime is developed against.

Everything downstream — nearest-node assignment, the canonical-position checksum the deformer
refuses on, the tileset Playwright loads from disk — trusts that these bytes are what the
generator says they are. So the tests check the properties the rest of the sprint leans on:
the output is reproducible, it round-trips through the real tiler, every splat has a known
owner, and the checksum agrees with the TypeScript implementation it is paired with.
"""

from __future__ import annotations

import gzip
import json
import struct
from pathlib import Path

import numpy as np
import pytest

import splat_tiles
import synthetic_tree

REPO_ROOT = Path(__file__).resolve().parents[3]
#: The committed fixture. Regenerated by:
#:   uv run python synthetic_tree.py ../../data/tiles/synthetic-tree --splats 12000
FIXTURE = REPO_ROOT / "data" / "tiles" / "synthetic-tree"
FIXTURE_SPLATS = 12000
FIXTURE_SEED = 7

GENERATE_DEFAULTS = {
    "splats": FIXTURE_SPLATS,
    "seed": FIXTURE_SEED,
    "lat": 28.0389,
    "lon": -82.6966,
    "height": 0.0,
    "height_m": 6.0,
    "geometric_error": 0.5,
}


def _files(root: Path) -> dict[str, bytes]:
    return {
        str(path.relative_to(root)): path.read_bytes()
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }


@pytest.fixture(scope="module")
def generated(tmp_path_factory: pytest.TempPathFactory) -> Path:
    out = tmp_path_factory.mktemp("tree")
    synthetic_tree.generate(out, **GENERATE_DEFAULTS)
    return out


# ------------------------------------------------------------------------------ determinism


def test_two_runs_produce_identical_bytes(tmp_path: Path) -> None:
    """PLY, rig, labels and tileset all byte-for-byte. splat_tiles pins gzip mtime=0 for
    exactly this reason; snapping positions to the SPZ grid keeps the rest stable."""
    first, second = tmp_path / "a", tmp_path / "b"
    synthetic_tree.generate(first, **GENERATE_DEFAULTS)
    synthetic_tree.generate(second, **GENERATE_DEFAULTS)
    left, right = _files(first), _files(second)
    assert sorted(left) == sorted(right)
    assert {"source/splat.ply", "source/rig.json", "splat/tileset.json", "splat/splat.glb"} <= set(
        left
    )
    for name in left:
        assert left[name] == right[name], f"{name} is not reproducible"


def test_a_different_seed_gives_a_different_tree(tmp_path: Path) -> None:
    """Otherwise 'deterministic' would be indistinguishable from 'ignores the seed'."""
    other = dict(GENERATE_DEFAULTS, seed=FIXTURE_SEED + 1)
    synthetic_tree.generate(tmp_path / "a", **GENERATE_DEFAULTS)
    synthetic_tree.generate(tmp_path / "b", **other)
    a = (tmp_path / "a" / "source" / "positions.f32").read_bytes()
    b = (tmp_path / "b" / "source" / "positions.f32").read_bytes()
    assert a != b


def test_committed_fixture_matches_the_generator(generated: Path) -> None:
    """The fixture in data/tiles/synthetic-tree is not hand-edited and is not stale."""
    assert _files(generated) == _files(FIXTURE)


# -------------------------------------------------------------------------------- round trip


def test_ply_reads_back_through_the_tiler(generated: Path) -> None:
    data = splat_tiles.read_ply(generated / "source" / "splat.ply")
    assert set(data) == set(synthetic_tree.PLY_PROPERTIES)
    for name, column in data.items():
        assert column.shape == (FIXTURE_SPLATS,), name
        assert np.isfinite(column).all(), name
    quat = np.stack([data[f"rot_{i}"] for i in range(4)], axis=1)
    assert np.allclose(np.linalg.norm(quat, axis=1), 1.0, atol=1e-6)
    opacity = splat_tiles.sigmoid(data["opacity"])
    assert opacity.min() > 0.02, "a splat below --opacity-min would be dropped by the tiler"


def test_the_tiler_keeps_every_splat(generated: Path, tmp_path: Path) -> None:
    """Ground-truth labels are in PLY order. splat_tiles preserves order but drops splats —
    finite, opacity and robust-radius masks — and a single drop shifts every later label."""
    stats = splat_tiles.convert(
        generated / "source" / "splat.ply",
        tmp_path / "splat",
        lat=0.0,
        lon=0.0,
        height=0.0,
        max_gaussians=FIXTURE_SPLATS,
        opacity_min=0.02,
        geometric_error=1.0,
    )
    assert stats["dropped"] == 0
    assert stats["gaussians"] == FIXTURE_SPLATS


def test_tileset_json_is_a_single_tile(generated: Path) -> None:
    """The deformer only supports single-tile splats; the fixture must not violate that."""
    tileset = json.loads((generated / "splat" / "tileset.json").read_text())
    assert "children" not in tileset["root"]
    assert tileset["root"]["content"]["uri"] == "splat.glb"
    assert len(tileset["root"]["transform"]) == 16


def test_positions_survive_spz_quantisation_unchanged(generated: Path) -> None:
    """Positions are snapped to the 1/4096 m SPZ grid before being written, so the decoded
    splats are bit-identical to the PLY floats and the checksum means the same thing on both
    sides of the tiler."""
    positions = _positions(generated)
    fixed = np.round(positions.astype(np.float64) * (1 << splat_tiles.SPZ_FRACTIONAL_BITS))
    decoded = (fixed / (1 << splat_tiles.SPZ_FRACTIONAL_BITS)).astype(np.float32)
    assert np.array_equal(decoded, positions)
    assert np.abs(fixed).max() < 2**23, "24-bit fixed point would overflow"
    # -0.0 equals 0.0 but has different bytes, and SPZ's integer round trip normalises it to
    # +0.0. One of them in the PLY would make the decoded splats fail the rig's checksum.
    assert not np.signbit(positions[positions == 0.0]).any()


# ---------------------------------------------------------------------------------- structure


def _positions(root: Path) -> np.ndarray:
    raw = np.frombuffer((root / "source" / "positions.f32").read_bytes(), dtype="<f4")
    return raw.reshape(-1, 3)


def _labels(root: Path) -> np.ndarray:
    return np.asarray(json.loads((root / "source" / "labels.json").read_text())["nodes"])


def _rig(root: Path) -> dict:
    return json.loads((root / "source" / "rig.json").read_text())


def test_positions_match_the_ply(generated: Path) -> None:
    data = splat_tiles.read_ply(generated / "source" / "splat.ply")
    xyz = np.stack([data["x"], data["y"], data["z"]], axis=1)
    assert np.array_equal(_positions(generated), xyz)


def test_every_splat_has_a_ground_truth_node(generated: Path) -> None:
    rig, labels = _rig(generated), _labels(generated)
    assert labels.shape == (FIXTURE_SPLATS,)
    assert labels.min() >= 0
    assert labels.max() < len(rig["nodes"])


def test_every_node_owns_at_least_one_splat(generated: Path) -> None:
    """A node with no splats moves nothing, which makes it an untestable part of the rig."""
    rig = _rig(generated)
    counts = np.bincount(_labels(generated), minlength=len(rig["nodes"]))
    empty = [rig["nodes"][i]["id"] for i, n in enumerate(counts) if n == 0]
    assert empty == []


def test_trunk_splats_are_below_the_canopy(generated: Path) -> None:
    rig, labels = _rig(generated), _labels(generated)
    bands = np.asarray([rig["nodes"][i]["band"] for i in labels])
    height = _positions(generated)[:, 2]
    assert height.min() >= 0.0
    assert height[bands == "trunk"].mean() < height[bands == "leaf"].mean()
    # The very bottom of the tree is trunk and nothing else: no foliage lying on the ground.
    assert set(bands[height < 0.5]) == {"trunk"}


def test_the_tree_stands_up_in_z(generated: Path) -> None:
    """+Z up, metre scale, local ENU — the frame @twin/world's deform assumes."""
    positions = _positions(generated)
    extent = positions.max(axis=0) - positions.min(axis=0)
    assert extent[2] > 0.9 * GENERATE_DEFAULTS["height_m"], "the tree should reach its height"
    assert extent[2] > extent[0] and extent[2] > extent[1]
    trunk_base = positions[positions[:, 2] < 0.3]
    assert np.abs(trunk_base[:, :2]).max() < 0.5, "the trunk should rise from the origin"


def test_nearest_node_assignment_mostly_recovers_the_truth(generated: Path) -> None:
    """Scores the runtime's algorithm (assignSplatsToNodes) against known truth rather than
    against itself. It is not expected to be perfect — a bark splat on the far side of the
    trunk is genuinely nearer its neighbour's node — but a fixture where it did badly would
    not be a useful thing to develop the deformer against."""
    rig, labels = _rig(generated), _labels(generated)
    nodes = np.asarray([node["position"] for node in rig["nodes"]])
    positions = _positions(generated).astype(np.float64)
    nearest = ((positions[:, None, :] - nodes[None, :, :]) ** 2).sum(axis=2).argmin(axis=1)
    assert (nearest == labels).mean() > 0.85


# ---------------------------------------------------------------------------------------- rig


def test_rig_is_structurally_valid(generated: Path) -> None:
    """The rules validateRig() enforces in packages/world/src/rig.ts, checked here too so a
    bad rig fails in the tool that produced it rather than three steps downstream."""
    rig = _rig(generated)
    assert rig["units"] == "meters"
    assert list(rig) == ["units", "canonicalChecksum", "sourceNote", "nodes"]
    nodes = rig["nodes"]
    assert 150 <= len(nodes) <= 65535
    assert nodes[0]["parent"] == -1
    seen: set[str] = set()
    for i, node in enumerate(nodes):
        assert node["id"] and node["id"] not in seen
        seen.add(node["id"])
        if i:
            assert 0 <= node["parent"] < i, "nodes must be in topological order"
        assert len(node["position"]) == 3
        assert all(np.isfinite(node["position"]))
        assert node["radius"] >= 0
        assert node["stiffness"] > 0
        assert node["band"] in {"trunk", "branch", "leaf"}


def test_rig_matches_the_typescript_generator(generated: Path) -> None:
    """syntheticTreeRig() in packages/world/src/rig.ts builds the same 214 nodes. The
    TypeScript side asserts the converse against this same file."""
    emitted = _rig(generated)["nodes"]
    mirrored = synthetic_tree.synthetic_tree_rig(height_m=6.0)["nodes"]
    assert [n["id"] for n in emitted] == [n["id"] for n in mirrored]
    assert len(emitted) == 214
    for a, b in zip(emitted, mirrored, strict=True):
        assert a["parent"] == b["parent"] and a["band"] == b["band"]
        assert a["position"] == pytest.approx(b["position"])


# ------------------------------------------------------------------ cross-language checksum


def test_checksum_covers_the_emitted_positions(generated: Path) -> None:
    rig = _rig(generated)
    assert rig["canonicalChecksum"] == synthetic_tree.checksum_positions(_positions(generated))
    assert rig["canonicalChecksum"].startswith(f"fnv1a32:{FIXTURE_SPLATS}:")


def test_checksum_notices_a_single_changed_bit(generated: Path) -> None:
    positions = _positions(generated).copy()
    positions[len(positions) // 2, 1] = np.float32(positions[len(positions) // 2, 1] + 2.0**-12)
    assert synthetic_tree.checksum_positions(positions) != _rig(generated)["canonicalChecksum"]


def test_checksum_vectors_are_self_consistent(generated: Path) -> None:
    """The committed vectors packages/world/src/rig.test.ts reads. If Python and TypeScript
    ever disagree, one side of this pair fails — which is the whole point of committing it."""
    cases = json.loads((generated / "source" / "checksum_vectors.json").read_text())["cases"]
    assert len(cases) >= 6
    names = {case["name"] for case in cases}
    assert {"empty", "origin", "negative-zero"} <= names
    for case in cases:
        positions = np.frombuffer(bytes.fromhex(case["positionsHex"]), dtype="<f4")
        assert synthetic_tree.checksum_positions(positions) == case["checksum"]
    # Positive and negative zero have different bytes, so they must checksum differently.
    by_name = {case["name"]: case["checksum"] for case in cases}
    assert by_name["negative-zero"] != by_name["origin"]
    assert by_name["empty"] == "fnv1a32:0:811c9dc5"


# ------------------------------------------------------------------------------- spz decoding


def _decode_glb_positions(path: Path) -> np.ndarray:
    """Positions back out of the tile, the way the engine gets them: GLB -> SPZ -> fixed point.

    The deformer's whole refusal mechanism rests on the decoded positions being the ones the
    checksum was taken over, so the claim is checked rather than asserted in a comment.
    """
    raw = path.read_bytes()
    assert raw[:4] == b"glTF"
    offset, chunks = 12, {}
    while offset < len(raw):
        length, kind = struct.unpack_from("<II", raw, offset)
        chunks[kind] = raw[offset + 8 : offset + 8 + length]
        offset += 8 + length
    gltf = json.loads(chunks[0x4E4F534A])
    view = gltf["bufferViews"][0]
    spz = gzip.decompress(
        chunks[0x004E4942][view["byteOffset"] : view["byteOffset"] + view["byteLength"]]
    )
    magic, version, count, _flags, fractional_bits = struct.unpack_from("<IIIBB", spz, 0)
    assert (magic, version) == (splat_tiles.SPZ_MAGIC, splat_tiles.SPZ_VERSION)
    assert fractional_bits == splat_tiles.SPZ_FRACTIONAL_BITS
    packed = np.frombuffer(spz, dtype=np.uint8, count=count * 9, offset=16).reshape(count, 3, 3)
    fixed = (
        packed[:, :, 0].astype(np.int32)
        | (packed[:, :, 1].astype(np.int32) << 8)
        | (packed[:, :, 2].astype(np.int32) << 16)
    )
    # 24-bit two's complement.
    fixed = np.where(fixed >= 1 << 23, fixed - (1 << 24), fixed)
    return (fixed / (1 << fractional_bits)).astype(np.float32)


def test_glb_decodes_to_exactly_the_checksummed_positions(generated: Path) -> None:
    decoded = _decode_glb_positions(generated / "splat" / "splat.glb")
    assert np.array_equal(decoded, _positions(generated))
    assert synthetic_tree.checksum_positions(decoded) == _rig(generated)["canonicalChecksum"]
