"""A paced Opus source containing only audio generated by the selected model."""
import asyncio
from fractions import Fraction
import time


def generated_audio_track(session, started):
    from aiortc import AudioStreamTrack
    from aiortc.mediastreams import MediaStreamError
    from av import AudioFrame

    class GeneratedAudioTrack(AudioStreamTrack):
        def __init__(self):
            super().__init__()
            self.index = -1
            self.offset = -1

        async def recv(self):
            while self.readyState == "live" and not session.stop.is_set():
                with session.lock:
                    audio, index, source_started = session.audio, session.audio_index, session.audio_started_at
                    running = session.resumed.is_set()
                if audio and running:
                    if index != self.index:
                        self.index, self.offset = index, -1
                    offset = max(0, int((time.monotonic() - source_started) * 48000) // 960 * 960)
                    if offset > self.offset and (offset + 960) * 4 <= len(audio):
                        self.offset = offset
                        frame = AudioFrame(format="s16", layout="stereo", samples=960)
                        frame.planes[0].update(audio[offset * 4:(offset + 960) * 4])
                        frame.sample_rate = 48000
                        frame.time_base = Fraction(1, 48000)
                        frame.pts = max(0, int((source_started - started) * 48000)) + offset
                        return frame
                await asyncio.sleep(0.005)
            raise MediaStreamError

    return GeneratedAudioTrack()
